set SynModuleInfo {
  {SRCNAME hevc_loop_filter_chroma_8bit_hls_Pipeline_VITIS_LOOP_87_2 MODELNAME hevc_loop_filter_chroma_8bit_hls_Pipeline_VITIS_LOOP_87_2 RTLNAME hevc_loop_filter_chroma_8bit_hls_hevc_loop_filter_chroma_8bit_hls_Pipeline_VITIS_LOOP_87_2
    SUBMODULES {
      {MODELNAME hevc_loop_filter_chroma_8bit_hls_flow_control_loop_pipe_sequential_init RTLNAME hevc_loop_filter_chroma_8bit_hls_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME hevc_loop_filter_chroma_8bit_hls_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME hevc_loop_filter_chroma_8bit_hls MODELNAME hevc_loop_filter_chroma_8bit_hls RTLNAME hevc_loop_filter_chroma_8bit_hls IS_TOP 1}
}
