#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_core", 8, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("ap_part", 8, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("ap_parent", 8, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("pix_base_address0", 21, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("pix_base_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("pix_base_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("pix_base_d0", 8, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("pix_base_q0", 8, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("pix_base_address1", 21, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("pix_base_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("pix_base_q1", 8, hls_in, 3, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("frame_offset", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("xstride", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("ystride", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("tc_arr_0", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("tc_arr_1", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("no_p_arr_0", 8, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("no_p_arr_1", 8, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("no_q_arr_0", 8, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("no_q_arr_1", 8, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("ap_ce", 1, hls_in, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "hevc_loop_filter_chroma_8bit_hls";
