#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_core", 8, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("ap_part", 8, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("ap_parent", 8, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("width", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("height", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("filter", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("pixel_address0", 13, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("pixel_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("pixel_q0", 8, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("pixel_address1", 13, hls_out, 6, "ap_memory", "MemPortADDR2", 1),
	Port_Property("pixel_ce1", 1, hls_out, 6, "ap_memory", "MemPortCE2", 1),
	Port_Property("pixel_we1", 1, hls_out, 6, "ap_memory", "MemPortWE2", 1),
	Port_Property("pixel_d1", 8, hls_out, 6, "ap_memory", "MemPortDIN2", 1),
	Port_Property("filter_map_address0", 6, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("filter_map_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("filter_map_q0", 8, hls_in, 7, "ap_memory", "mem_dout", 1),
	Port_Property("sum_address0", 12, hls_out, 8, "ap_memory", "mem_address", 1),
	Port_Property("sum_ce0", 1, hls_out, 8, "ap_memory", "mem_ce", 1),
	Port_Property("sum_we0", 1, hls_out, 8, "ap_memory", "mem_we", 1),
	Port_Property("sum_d0", 32, hls_out, 8, "ap_memory", "mem_din", 1),
	Port_Property("sum_q0", 32, hls_in, 8, "ap_memory", "mem_dout", 1),
	Port_Property("sum_address1", 12, hls_out, 8, "ap_memory", "MemPortADDR2", 1),
	Port_Property("sum_ce1", 1, hls_out, 8, "ap_memory", "MemPortCE2", 1),
	Port_Property("sum_we1", 1, hls_out, 8, "ap_memory", "MemPortWE2", 1),
	Port_Property("sum_d1", 32, hls_out, 8, "ap_memory", "MemPortDIN2", 1),
	Port_Property("ap_ce", 1, hls_in, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "cnn_hls";
