#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_core", 8, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("ap_part", 8, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("ap_parent", 8, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("in_data_address0", 10, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("in_data_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("in_data_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("in_w", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("in_h", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("kernel_address0", 5, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("kernel_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("kernel_q0", 64, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("kernel_w", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("kernel_h", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("out_data_address0", 10, hls_out, 9, "ap_memory", "mem_address", 1),
	Port_Property("out_data_ce0", 1, hls_out, 9, "ap_memory", "mem_ce", 1),
	Port_Property("out_data_we0", 1, hls_out, 9, "ap_memory", "mem_we", 1),
	Port_Property("out_data_d0", 64, hls_out, 9, "ap_memory", "mem_din", 1),
	Port_Property("out_data_q0", 64, hls_in, 9, "ap_memory", "mem_dout", 1),
	Port_Property("out_w", 32, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("out_h", 32, hls_in, 11, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "convn_valid";
